### PR TITLE
Missing key parameter on clear method.

### PR DESCRIPTION
**Pull request by appleboy**
* Add clear key as parameter
* Add testing for stable node version.

cc @cayasso

### CODE REVIEW

**Comment by cayasso** [comment]
@appleboy that is why the `del` method exist.

**Comment by appleboy** [comment]
@cayasso 

If I want to delete `test0*` prefix name as key, how to delete using `del` method on redis?

**Comment by cayasso** [comment]
Sorry @appleboy I just realised the confusion, by mistake I left `key` as 1st arguments but even do the docs have it right, this is a bug in the code I will need to fix, the intend of the `clear` method is to clear all keys and `delete` method to delete the specified key only, and this should be consistent on all engines.

thanks for raising this issue.

I will also fix the issue above in the Redis engine

**Comment by appleboy** [comment]
@cayasso so if I want to clear key with glob-style patterns. How to resolve in `redis` engine with `del` method?

**Comment by appleboy** [comment]
You will integrate del method with glob-style patterns on redis engine. Right?

**Pull request closed without merging**
