### PR TITLE
Change cacheman constructor to more intuitively manage key prefixes.

### PR DESCRIPTION
**Pull request by mdurling**
new Cacheman() will yield cacheman:cache:XXXX keys
new Cacheman('name') will yield cacheman:name:XXXX keys
new Cacheman('name', { prefix: 'prefix' }) will yield prefix:name:XXX keys

### CODE REVIEW

**Comment by cayasso** [comment]
I definitely like this, can you add some test cases?

**Comment by mdurling** [comment]
Hi.

I was going to add some tests this morning, but it appears you already did
so.

I see you've merged the PR. Can you issue a release?

Cheers,
Michael

**Comment by cayasso** [comment]
@mdurling sorry for the delay cacheman@2.1.0 is out.

**Comment by mdurling** [comment]
When using cacheman, if cachman is going to apply a prefix to the key then it should instruct the engine to not apply a prefix. Since the engines can be used directly or via cacheman, I would advocate either A) cacheman applies the prefix and does not set the engine prefix, or B) cacheman does not apply the prefix, but sets the prefix to be used by the engine. The current implementation yields keys with duplicated prefix resulting in keys that look like: prefix:name:prefix:name:XXXX when they should really just be prefix:name:XXXX

screen shot 2016-01-15 at 9 30 59 am

**Pull request merged**
